export const movies = [
  {
    "id": 13,
    "title": "Inception",
    "year": 2010,
    "imdbRating": 8.8,
    "genre": ["Action", "Adventure", "Sci-Fi"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_FMjpg_UX1000_.jpg",
    "link": "http://asilmedia.org/10761-muqaddima-uzbek-tilida-2010-ozbek-tarjima-kino-hd.html"
  },
  {
    "id": 61,
    "title": "Titanic",
    "year": 1997,
    "imdbRating": 7.9,
    "genre": ["Drama", "Romance"],
    "country": "USA",
    "language": "English",
    "poster": "https://public-website-assets.paramountpictures.com/paramount2025/s3fs-public/styles/poster_medium/public/titanic2012_en_800x1200.jpg?itok=lbdE3VIG",
    "link": "http://asilmedia.org/9516-titanik-uzbekcha-tarjima-1997-ozbek-tilida-titanik-titanic-tas-ix-skachat.html"
  },
  {
    "id": 3,
    "title": "The Dark Knight",
    "year": 2008,
    "imdbRating": 9.0,
    "genre": ["Action", "Crime", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTk4ODQzNDY3Ml5BMl5BanBnXkFtZTcwODA0NTM4Nw@@._V1_FMjpg_UX1000_.jpg",
    "link": "http://asilmedia.org/8580-betmen-jokerga-qarshi-qora-ritsar-temnyy-rycar-betmen-protiv-dzhokera-hd-uzbek-ozbek-tilida-tas-ix-skachat-download.html"
  },
  {
    "id": 45,
    "title": "Harry Potter and the Prisoner of Azkaban",
    "year": 2004,
    "imdbRating": 7.9,
    "genre": ["Adventure", "Family", "Fantasy"],
    "country": "UK",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/I/A12o-S9zoFL._AC_UF894,1000_QL80_.jpg",
    "link": "http://asilmedia.org/9062-garri-potter-3-azkaban-mahbusi-uzbek-tarjima-2004-hd-ozbek-tilida-tas-ix-skachat.html"
  },
  {
    "id": 2,
    "title": "The Godfather",
    "year": 1972,
    "imdbRating": 9.2,
    "genre": ["Crime", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "link": "http://asilmedia.org/9057-choqintirgan-ota-1-uzbek-tarjima-1972-hd-ozbek-tilida-tas-ix-skachat.html"
  },
  {
    "id": 56,
    "title": "Fast & Furious 6",
    "year": 2013,
    "imdbRating": 7.0,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTM3NTg2NDQzOF5BMl5BanBnXkFtZTcwNjc2NzQzOQ@@._V1_FMjpg_UX1000_.jpg",
    "link": "http://asilmedia.org/8570-forsaj-6-uzbek-ozbek-tilida-tas-ix-skachat-download.html"
  },
  {
    "id": 10,
    "title": "The Good, the Bad and the Ugly",
    "year": 1966,
    "imdbRating": 8.8,
    "genre": ["Adventure", "Western"],
    "country": "Italy",
    "language": "Italian",
    "poster": "https://m.media-amazon.com/images/I/71HA2V6PaTL._AC_UF894,1000_QL80_.jpg",
    "link": "http://asilmedia.org/1785-yahshi-emon-va-badzhal.html"
  },
  {
    "id": 50,
    "title": "Harry Potter and the Deathly Hallows: Part 2",
    "year": 2011,
    "imdbRating": 8.1,
    "genre": ["Adventure", "Family", "Fantasy"],
    "country": "UK",
    "language": "English",
    "poster": "https://moviesmedia.ign.com/movies/image/object/143/14325037/HP&2-FB-poster.jpg",
    "link": "http://asilmedia.org/5043-harry-potter-and-the-deathly-hallows-part-2.html"
  },
  {
    "id": 42,
    "title": "F1 (Formula 1)",
    "year": 2025,
    "imdbRating": 7.8,
    "genre": ["Action", "Drama", "Sport"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGI0MDI4NjEtOWU3ZS00ODQyLWFhYTgtNGYxM2ZkM2Q2YjE3XkEyXkFqcGc@._V1_.jpg",
    "link": "http://asilmedia.org/17294-f1-formula-1-2025-uzbek-tilida-ozbekcha-tarjima-kino-full-hd-tas-ix-skachat.html"
  },
  {
    "id": 1,
    "title": "The Shawshank Redemption",
    "year": 1994,
    "imdbRating": 9.3,
    "genre": ["Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "link": "http://asilmedia.org/7540-shoushenkdan-qochsih-uzbek-ozbek-tilida-tas-ix-skachat-download.html"
  },
  {
    "id": 55,
    "title": "Fast Five",
    "year": 2011,
    "imdbRating": 7.3,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p8338313_p_v10_bb.jpg",
    "link": "http://asilmedia.org/8564-forsaj-5-uzbek-ozbek-tilida-tas-ix-skachat-download.html"
  },
  {
    "id": 26,
    "title": "Interstellar",
    "year": 2014,
    "imdbRating": 8.7,
    "genre": ["Adventure", "Drama", "Sci-Fi"],
    "country": "USA",
    "language": "English",
    "poster": "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
    "link": "http://asilmedia.org/9140-interstellar-uzbek-tarjima-2014-hd-ozbek-tilida-tas-ix-skachat.html"
  },
  {
    "id": 40,
    "title": "Joker",
    "year": 2019,
    "imdbRating": 8.4,
    "genre": ["Crime", "Drama", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/e/e1/Joker_%282019_film%29_poster.jpg/250px-Joker_%282019_film%29_poster.jpg",
    "link": "http://asilmedia.org/9242-joker-uzbek-tarjima-2019-hd-ozbek-tilida-tas-ix-skachat.html"
  },
  {
    "id": 7,
    "title": "The Lord of the Rings: The Return of the King",
    "year": 2003,
    "imdbRating": 9.0,
    "genre": ["Action", "Adventure", "Drama"],
    "country": "New Zealand",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "link": "http://asilmedia.org/4995-the-lord-of-the-rings-the-return-of-the-king.html"
  },
  {
    "id": 36,
    "title": "Parasite",
    "year": 2019,
    "imdbRating": 8.5,
    "genre": ["Comedy", "Drama", "Thriller"],
    "country": "South Korea",
    "language": "Korean",
    "poster": "https://s3.amazonaws.com/nightjarprod/content/uploads/sites/130/2024/03/29150816/7IiTTgloJzvGI1TAYymCfbfl3vT-scaled.jpg",
    "link": "http://asilmedia.org/10518-parazit-uzbek-tilida-ozbekcha-tarjima-kino-2019-hd.html"
  },
  {
    "id": 51,
    "title": "The Fast and the Furious",
    "year": 2001,
    "imdbRating": 6.8,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSupbLQsRlP0xj_MP1_J1lHE5Ex1mPHsmlbmA&s",
    "link": "http://asilmedia.org/8563-forsaj-1-uzbek-ozbek-tilida-tas-ix-skachat-download.html"
  },
  {
    "id": 12,
    "title": "Fight Club",
    "year": 1999,
    "imdbRating": 8.8,
    "genre": ["Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg",
    "link": "http://asilmedia.org/17749-jang-klubi-kurash-guruhi-1999-uzbek-tilida-ozbekcha-tarjima-kino-full-hd-tas-ix-skachat.html"
  },
  {
    "id": 4,
    "title": "The Godfather Part II",
    "year": 1974,
    "imdbRating": 9.0,
    "genre": ["Crime", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://asilmedia.org/uploads/mini/fullstory/dc/x59b5c64a62c96b7014fdfbd4152636.jpg.pagespeed.ic.Pm9z689Y0v.jpg",
    "link": "http://asilmedia.org/9058-choqintirgan-ota-2-uzbek-tarjima-1974-hd-ozbek-tilida-tas-ix-skachat.html"
  },
  {
    "id": 49,
    "title": "Harry Potter and the Deathly Hallows: Part 1",
    "year": 2010,
    "imdbRating": 7.7,
    "genre": ["Adventure", "Family", "Fantasy"],
    "country": "UK",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTQ2OTE1Mjk0N15BMl5BanBnXkFtZTcwODE3MDAwNA@@._V1_.jpg",
    "link": "https://uzmovi.tv/jangari/1246-garri-potter-1-2-3-4-5-6-7-8-barcha-qismlari-uzbek-tilida/episode/13811/7.html"
  },
  {
    "id": 34,
    "title": "Gladiator",
    "year": 2000,
    "imdbRating": 8.5,
    "genre": ["Action", "Adventure", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://files.itv.uz/uploads/content/poster/2023/09/19/c5a408ba057c2790afd09a7fe0868999-q-700x1002.jpeg",
    "link": "http://asilmedia.org/7922-gladiator-uzbek-ozbek-tilida-tas-ix-skachat-download.html"
  },
  {
    "id": 11,
    "title": "Forrest Gump",
    "year": 1994,
    "imdbRating": 8.8,
    "genre": ["Drama", "Romance"],
    "country": "USA",
    "language": "English",
    "poster": "https://public-website-assets.paramountpictures.com/paramount2025/s3fs-public/styles/poster_medium/public/forrestgump_2019update_en_800x1200.jpg?itok=wqyuMS2H",
    "link": "http://asilmedia.org/9759-forrest-gamp-uzbek-tilida-1994-ozbekcha-tarjima-tas-ix-skachat.html"
  },
  {
    "id": 57,
    "title": "Furious 7",
    "year": 2015,
    "imdbRating": 7.1,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/I/81qSIqOes-L._AC_UF894,1000_QL80_.jpg",
    "link": "http://asilmedia.org/2370-forsaj-7-forsazh-7-ozbek-tilida-tas-ix.html"
  },
  {
    "id": 9,
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "year": 2001,
    "imdbRating": 8.9,
    "genre": ["Action", "Adventure", "Drama"],
    "country": "New Zealand",
    "language": "English",
    "poster": "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p28828_p_v8_ao.jpg",
    "link": "http://asilmedia.org/4992-the-lord-of-the-rings-the-fellowship-of-the-ring.html"
  },
  {
    "id": 41,
    "title": "Robinson Crusoe",
    "year": 1997,
    "imdbRating": 6.0,
    "genre": ["Adventure", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMTdjYjMxZDEtZmU0Yy00OGQ3LWEyODAtMGM5NTRjY2YxZTQ5XkEyXkFqcGc@._V1_.jpg",
    "link": "http://asilmedia.org/17041-robinzon-kruzo-aqsh-retro-filmi-uzbek-tilida-1997-ozbekcha-tarjima-kino-full-hd-tas-ix-skachat.html"
  },
  {
    "id": 20,
    "title": "Se7en",
    "year": 1995,
    "imdbRating": 8.6,
    "genre": ["Crime", "Drama", "Mystery"],
    "country": "USA",
    "language": "English",
    "poster": "https://upload.wikimedia.org/wikipedia/ru/thumb/8/83/Se7en_%28poster%29.jpg/250px-Se7en_%28poster%29.jpg",
    "link": "http://asilmedia.org/15841-yetti-se7en-uzbek-tilida-1995-ozbekcha-tarjima-kino-hd.html"
  },
  {
    "id": 52,
    "title": "2 Fast 2 Furious",
    "year": 2003,
    "imdbRating": 5.9,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BOTQzYzEwNWMtOTAwYy00YWYwLWE1NTEtZTkxOGQxZTM0M2VhXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "link": "http://asilmedia.org/11399-forsaj-2-uzbek-tilida-2003-ozbekcha-tarjima-kino-hd.html"
  },
  {
    "id": 44,
    "title": "Harry Potter and the Chamber of Secrets",
    "year": 2002,
    "imdbRating": 7.4,
    "genre": ["Adventure", "Family", "Fantasy"],
    "country": "UK",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGJhM2M2MWYtZjIzMC00MDZmLThkY2EtOWViMDhhYjRhMzk4XkEyXkFqcGc@._V1_.jpg",
    "link": "https://uzmovi.tv/jangari/1246-garri-potter-1-2-3-4-5-6-7-8-barcha-qismlari-uzbek-tilida/episode/13811/2.html"
  },
  {
    "id": 35,
    "title": "The Lion King",
    "year": 1994,
    "imdbRating": 8.5,
    "genre": ["Animation", "Adventure", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://lumiere-a.akamaihd.net/v1/images/p_thelionking_19752_1_0b9de87b.jpeg",
    "link": "http://asilmedia.org/10446-qirol-sher-1-480p-multfilm-uzbek-tilida-1994.html"
  },
  {
    "id": 16,
    "title": "The Matrix",
    "year": 1999,
    "imdbRating": 8.7,
    "genre": ["Action", "Sci-Fi"],
    "country": "USA",
    "language": "English",
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfSjSWOCaw5dnDL2GT1zFd9RMCgUGw5Q2Cfg&s",
    "link": "http://asilmedia.org/8103-the-matrix.html"
  },
  {
    "id": 58,
    "title": "The Fate of the Furious",
    "year": 2017,
    "imdbRating": 6.6,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/I/81nEFN2HHuL._AC_UF894,1000_QL80_.jpg",
    "link": "https://asilmedia.net/6381-forsaj-8-the-fate-of-the-furious-2017.html"
  },
  {
    "id": 32,
    "title": "The Pianist",
    "year": 2002,
    "imdbRating": 8.5,
    "genre": ["Biography", "Drama", "War"],
    "country": "Poland",
    "language": "German",
    "poster": "https://upload.wikimedia.org/wikipedia/en/a/a6/The_Pianist_movie.jpg",
    "link": "https://asilmedia.net/830-pianinochi-the-pianist-2002.html"
  },
  {
    "id": 46,
    "title": "Harry Potter and the Goblet of Fire",
    "year": 2005,
    "imdbRating": 7.7,
    "genre": ["Adventure", "Family", "Fantasy"],
    "country": "UK",
    "language": "English",
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9UKus0XjHjPPNwr80LElFSRX0hRiqQvBerQ&s",
    "link": "https://asilmedia.net/821-garri-potter-va-olov-kubogi-harry-potter-and-the-goblet-of-fire-2005.html"
  },
  {
    "id": 14,
    "title": "The Lord of the Rings: The Two Towers",
    "year": 2002,
    "imdbRating": 8.8,
    "genre": ["Action", "Adventure", "Drama"],
    "country": "New Zealand",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_.jpg",
    "link": "https://asilmedia.net/812-uzuklar-hukmdori-2-ikki-qal-a-the-lord-of-the-rings-the-two-towers-2002.html"
  },
  {
    "id": 53,
    "title": "The Fast and the Furious: Tokyo Drift",
    "year": 2006,
    "imdbRating": 6.0,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTaY3IKN1yJ1LtdA81dk1TZNCL3RtA3ovrabA&s",
    "link": "https://asilmedia.net/6376-forsaj-3-tokio-drifti-the-fast-and-the-furious-tokyo-drift-2006.html"
  },
  {
    "id": 25,
    "title": "Léon: The Professional",
    "year": 1994,
    "imdbRating": 8.5,
    "genre": ["Action", "Crime", "Drama"],
    "country": "France",
    "language": "English",
    "poster": "https://images.uzmovi.tv/ii/1596648511/2e9961e5/31263636.jpg",
    "link": "https://asilmedia.net/403-leon-leon-the-professional-1994.html"
  },
  {
    "id": 59,
    "title": "F9: The Fast Saga",
    "year": 2021,
    "imdbRating": 5.2,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6MvKxT-xZVhfaI9c_zQi0XpdNG9g7O67BwA&s",
    "link": "https://asilmedia.net/7403-forsaj-9-f9-the-fast-saga-2021.html"
  },
  {
    "id": 17,
    "title": "Goodfellas",
    "year": 1990,
    "imdbRating": 8.7,
    "genre": ["Biography", "Crime", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "link": "https://asilmedia.net/963-shovvozlar-goodfellas-1990.html"
  },
  {
    "id": 48,
    "title": "Harry Potter and the Half-Blood Prince",
    "year": 2009,
    "imdbRating": 7.6,
    "genre": ["Adventure", "Family", "Fantasy"],
    "country": "UK",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BNzU3NDg4NTAyNV5BMl5BanBnXkFtZTcwOTg2ODg1Mg@@._V1_FMjpg_UX1000_.jpg",
    "link": "https://asilmedia.net/823-garri-potter-va-yarim-qon-shahzoda-harry-potter-and-the-half-blood-prince-2009.html"
  },
  {
    "id": 30,
    "title": "Terminator 2: Judgment Day",
    "year": 1991,
    "imdbRating": 8.6,
    "genre": ["Action", "Sci-Fi"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BNGMyMGNkMDUtMjc2Ni00NWFlLTgyODEtZTY2MzBiZTg0OWZiXkEyXkFqcGc@._V1_.jpg",
    "link": "https://asilmedia.net/513-terminator-2-qiyomat-kuni-terminator-2-judgment-day-1991.html"
  },
  {
    "id": 54,
    "title": "Fast & Furious 4",
    "year": 2009,
    "imdbRating": 6.6,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Fast_and_Furious_Poster.jpg/250px-Fast_and_Furious_Poster.jpg",
    "link": "https://asilmedia.net/6377-forsaj-4-fast-furious-4-2009.html"
  },
  {
    "id": 31,
    "title": "Back to the Future",
    "year": 1985,
    "imdbRating": 8.5,
    "genre": ["Adventure", "Comedy", "Sci-Fi"],
    "country": "USA",
    "language": "English",
    "poster": "https://images.squarespace-cdn.com/content/5c62c09c4d546e27dc1016c7/1556601485984-3DTSI22OZXMHROZRBNBD/bttf3.jpg?format=500w",
    "link": "https://asilmedia.net/313-kelajakka-qaytib-1-back-to-the-future-1985.html"
  },
  {
    "id": 8,
    "title": "Pulp Fiction",
    "year": 1994,
    "imdbRating": 8.9,
    "genre": ["Crime", "Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://www.tallengestore.com/cdn/shop/products/PulpFiction-JohnTravoltaAndSamuelLJackson-MovieStill1_e45cd25a-1957-4847-8b88-d2939a633e1d.jpg?v=1684129890",
    "link": "https://asilmedia.net/1531-jinoiy-asarlar-pulp-fiction-1994.html"
  },
  {
    "id": 47,
    "title": "Harry Potter and the Order of the Phoenix",
    "year": 2007,
    "imdbRating": 7.5,
    "genre": ["Adventure", "Family", "Fantasy"],
    "country": "UK",
    "language": "English",
    "poster": "https://avatars.mds.yandex.net/get-kinopoisk-image/4303601/1c8e7019-20c6-4bfb-ad17-6b7746ca5147/220x330",
    "link": "https://asilmedia.net/822-garri-potter-va-feniks-ordeni-harry-potter-and-the-order-of-the-phoenix-2007.html"
  },
  {
    "id": 21,
    "title": "The Silence of the Lambs",
    "year": 1991,
    "imdbRating": 8.6,
    "genre": ["Crime", "Drama", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXD5EzCfvxKSqbAfp8BlsWjDQumsX0S9rYVg&s",
    "link": "https://asilmedia.net/1423-qo-zilar-sukunati-the-silence-of-the-lambs-1991.html"
  },
  {
    "id": 60,
    "title": "Fast X",
    "year": 2023,
    "imdbRating": 5.8,
    "genre": ["Action", "Crime", "Thriller"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/S/pv-target-images/2cb257f2498be66f7d83221efcfe5ef99e7c62e17e19bddee4d36dbc84a92464.jpg",
    "link": "https://asilmedia.net/11181-forsaj-10-fast-x-2023.html"
  },
  {
    "id": 39,
    "title": "Whiplash",
    "year": 2014,
    "imdbRating": 8.5,
    "genre": ["Drama", "Music"],
    "country": "USA",
    "language": "English",
    "poster": "https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p10488558_p_v12_ai.jpg",
    "link": "https://asilmedia.net/1440-qamchi-whiplash-2014.html"
  },
  {
    "id": 6,
    "title": "Schindler's List",
    "year": 1993,
    "imdbRating": 9.0,
    "genre": ["Biography", "Drama", "History"],
    "country": "USA",
    "language": "English",
    "poster": "https://upload.wikimedia.org/wikipedia/en/3/38/Schindler%27s_List_movie.jpg",
    "link": "https://asilmedia.net/402-shindler-ro-yxati-schindlers-list-1993.html"
  },
  {
    "id": 19,
    "title": "Seven Samurai",
    "year": 1954,
    "imdbRating": 8.6,
    "genre": ["Action", "Drama"],
    "country": "Japan",
    "language": "Japanese",
    "poster": "https://m.media-amazon.com/images/M/MV5BZDg4MTYyYjktZGJiYy00ZGIwLWEzNTMtNTZkMjRhYTViMWE4XkEyXkFqcGc@._V1_.jpg",
    "link": "https://asilmedia.net/index.php?do=search&subaction=search&story=Seven+Samurai"
  },
  {
    "id": 18,
    "title": "One Flew Over the Cuckoo's Nest",
    "year": 1975,
    "imdbRating": 8.7,
    "genre": ["Drama"],
    "country": "USA",
    "language": "English",
    "poster": "https://m.media-amazon.com/images/M/MV5BYjBkMjgzMzYtNzRiMS00NDc3LWE4YTUtZjYxYjZhNjNhYzhhXkEyXkFqcGc@._V1_.jpg",
    "link": "https://asilmedia.net/400-kakku-uyasi-uzra-parvoz-one-flew-over-the-cuckoos-nest-1975.html"
  }


];